### ISSUE TITLE
Can not find user.db and no output

### ISSUE THREAD

**Issue by theLSA** [bitsadmin/fakelogonscreen#3]
Hi, good project!
But I encounter some problems.

win10:
When I use FakeLogonScreenToFile.exe, I can not find user.db in %LOCALAPPDATA%\Microsoft\user.db, and console output is empty.
When I use FakeLogonScreen.exe, console output is empty too.
![fakelogonscreen-problem-03](https://user-images.githubusercontent.com/28248956/83333405-d8104c00-a2d2-11ea-807a-117d6e43dbc2.png)

win7:
When I use FakeLogonScreenToFile.exe, console output is empty, But I can find user.db in %LOCALAPPDATA%\Microsoft\user.db through search tool. (Can not find in windows file manager even allow show hide file)
When I use FakeLogonScreen.exe, console output is empty.
//donet35 have some problem
![fakelogonscreen-problem-01](https://user-images.githubusercontent.com/28248956/83333287-5b7d6d80-a2d2-11ea-8bf3-ab9b57d2bfc5.png)
![fakelogonscreen-problem-02](https://user-images.githubusercontent.com/28248956/83333288-5ddfc780-a2d2-11ea-8a77-7589246c7a86.png)

**Comment by bitsadmin** [comment]
The user.db file is marked as both 'hidden' and 'system' so in addition to showing the hidden folders, you also need to uncheck Folder Options -> View tab -> 'Hide protected operating system files'.

Regarding the console output, this doesn't work in a regular console because the stdout of the FakeLogonScreen.exe application is not connected in cmd.exe. Instead you need to use for example a Metasploit or Cobalt Strike reverse shell. See some examples on YouTube: https://www.youtube.com/results?search_query=bitsadmin+fakelogonscreen.
